name: Release Windows build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: app
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Enable Git LFS
        run: git lfs install

      - name: Pull LFS files
        run: git lfs pull

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: app/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build app (Vite + TS)
        run: npm run build

      - name: Package Windows artifacts (no publish)
        run: npx electron-builder -c electron-builder.yml -w --publish never

      - name: Upload Windows artifacts to GitHub Release (clobber)
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          TAG="${GITHUB_REF_NAME:-${GITHUB_REF##*/}}"
          gh release view "$TAG" >/dev/null 2>&1 || gh release create "$TAG" -t "$TAG" -n ""
          gh release upload "$TAG" release/* --clobber

      - name: Upload artifacts (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: windows-dist
          path: app/release/**
          if-no-files-found: ignore
