name: Release Windows build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: app
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Enable Git LFS
        run: git lfs install

      - name: Pull LFS files
        run: git lfs pull

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: app/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build app (Vite + TS)
        run: npm run build

      - name: Package Windows artifacts (no publish)
        run: npx electron-builder -c electron-builder.yml -w --publish never

      - name: Upload Windows artifacts to GitHub Release (clobber)
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $ErrorActionPreference = 'Stop'
          $tag = "$env:GITHUB_REF_NAME"
          if (-not $tag -and $env:GITHUB_REF) { $tag = $env:GITHUB_REF -replace '^refs/tags/', '' }
          if (-not $tag) { throw "Cannot determine tag name" }
          gh release view $tag 2>$null | Out-Null
          if ($LASTEXITCODE -ne 0) { gh release create $tag -t $tag -n "" }
          Get-ChildItem -LiteralPath "release" -File | ForEach-Object {
            gh release upload $tag $_.FullName --clobber
          }

      - name: Upload artifacts (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: windows-dist
          path: app/release/**
          if-no-files-found: ignore
